### ISSUE TITLE
Add a page showing realtime IMU data

### ISSUE THREAD

**Issue by sarfata** [sarfata/kbox-firmware#10]
So that users can look at it in realtime and make sure everything is working well.

The IMU should show:
- Current pitch
- Current yaw
- Current roll
- Current magnetic course

**Comment by CaptainRon47** [comment]
My suggestion is to have the KBox display pages cycle thru several pages on a timed cycle (releasing the push button for other options).  It could show the current two pages plus pages for all instrument data (wind, barometric pressure, IMU data, etc).

**Comment by sarfata** [comment]
(removing barometer from this ticket - i will create another one for that)
