### ISSUE TITLE
Network streams are interrupted after a period of time

### ISSUE THREAD

**Issue by sarfata** [sarfata/kbox-firmware#116]
After a few minutes connected to the TCP NMEA output or the WebSocket output, the connection stops and has to be restarted.

We need to investigate what is going on and make sure this does not happen.

Tested on the wifi config branch.

**Comment by ronzeiller** [comment]
The interesting thing is: 
* if only NMEA sentences are sent then telnet stops after short time with "closed by foreign host"
* But, if NMEA and PCDIN are sent, then it works for longer.

(Tested on #119 which is based on master)

**Comment by sarfata** [comment]
closed by #127
