### ISSUE TITLE
WiFi upload should work with platformio esptool

### ISSUE THREAD

**Issue by sarfata** [sarfata/kbox-firmware#2]
The version of the esp-tool embedded in platformio does not work with our `program-esp` firmware. This is probably a timing issue, but needs to be debugged.

The work-around is to use another esp programmer, as demonstrated in the [Makefile](https://github.com/sarfata/kbox-firmware/blob/master/Makefile#L13) but that only works on Linux and Mac OS.

**Comment by CK0y0TE** [comment]
Workaround confirmed working. 
AP name/ password change succes.
