### ISSUE TITLE
update documentation for signalk-server-node integration

### ISSUE THREAD

**Issue by lfrancois** [sarfata/kbox-firmware#41]
Hi @sarfata! I have some notes for the wiki to get the kbox up and running with signalk-server-node. Please find them enclosed.

[kbox-signalk-setup-doc_wiki_2017-08-20.txt](https://github.com/sarfata/kbox-firmware/files/1236909/kbox-signalk-setup-doc_wiki_2017-08-20.txt)

**Comment by sarfata** [comment]
Added in a new specific page. Thanks a lot!

https://github.com/sarfata/kbox-firmware/wiki/signalk-server

And there is a link directly from the wiki home.
