### ISSUE TITLE
kbox internal sensors data not available anymore from 10110

### ISSUE THREAD

**Issue by lfrancois** [sarfata/kbox-firmware#42]
Hi @sarfata ! It seems the kbox stopped to forward its internal data, temperature, fake humidity, barometric pressure... Any idea how it could have happened? I am running the dev branch.

Everything else looks correctly forwarded.

Please find enclosed some output from the kbox.

[kbox_logs_2017-08-20.txt.zip](https://github.com/sarfata/kbox-firmware/files/1236988/kbox_logs_2017-08-20.txt.zip)

**Comment by sarfata** [comment]
Yeah I stopped sending it because I did not think it was very useful. Do you miss it? Can bring it back :)

What format would you like? PCDIN sentences or a NMEA sentence?

**Comment by lfrancois** [comment]
PCDIN sentences works for me. Barometric pressure sounds useful. Do you get it from other devices? I need to check what else is covered in the code.

**Comment by sarfata** [comment]
Solved in #49
