### ISSUE TITLE
N2k Message for IMU in degrees instead of radians

### ISSUE THREAD

**Issue by ronzeiller** [sarfata/kbox-firmware#46]
in the NMEA2000Task.cpp seems to be a bug, as there is sent degrees to form N2k-Sentences.

Shouldnt be there a DegToRad as:
```
SetN2kAttitude(n2kmessage, _imuSequence, DegToRad( m.getYaw() ), DegToRad( m.getPitch() ), DegToRad( m.getRoll() ) );
    sendN2kMessage(n2kmessage);

    double magneticVariation = N2kDoubleNA;
    double magneticDeviation = N2kDoubleNA;

    SetN2kMagneticHeading(n2kmessage, _imuSequence, DegToRad( m.getCourse() ), magneticDeviation, magneticVariation);
```
Tested with Actisense NGT-1 and NMEA Reader shows correct values then.

**Comment by sarfata** [comment]
KBox should use radians everywhere internally. 

In the IMUTask we already receive angles as radians, and do not convert them to degree:
https://github.com/sarfata/kbox-firmware/blob/master/lib/KBox/src/tasks/IMUTask.cpp#L50

So we should not need to convert when sending the message to the bus... Maybe my mistake is I assumed the BNO055 driver returned angles in radians but it sends them in degrees instead.

I have been traveling for work for the last 2 weeks and do not have a KBox with me but I will look into this when I get back next week. Thanks a lot!
