### ISSUE TITLE
Bugfix for NMEA sentence length

### ISSUE THREAD

**Issue by ronzeiller** [sarfata/kbox-firmware#58]
The $GPGGA sentence is _"Discarding incomplete sequence"_

I think it should be:
#define MAX_NMEA_SENTENCE_LENGTH 83

in NMEAService.h
Defined by the NMEA Standard is 82 plus 1 needed for termination of string?

**Comment by sarfata** [comment]
Good catch! Thanks!

@ronzeiller do you have an example of a valid sentence that got rejected? I would like to add it to my tests.
