### ISSUE TITLE
Send IMU data to NMEA2000

### ISSUE THREAD

**Issue by sarfata** [sarfata/kbox-firmware#6]
PGN 127250, 127251 and 127257 based on IMU data are respectively Magnetic heading, Rate of turn and Attitude.

See https://github.com/sarfata/kbox-firmware/wiki/Supported-PGNs

- 127250 and 127251 are supported by NMEA2000
- 127257 is not yet supported (see ttlappalainen/NMEA2000#10)

**Comment by beaugunderson** [comment]
Noting that 127257 is now supported. :)

**Comment by sarfata** [comment]
Creating new issues to keep track of the things that were not included here: Yaw (#23) and Rate of turn (#22).

**Comment by sarfata** [comment]
Attitude and heading tested with canboat analyzer :white_check_mark: 

Magnetic heading tested on Raymarine i70: it works but incorrectly shows the heading as True.
Attitude tested on Raymarine i70: tilt is available. Roll and yaw do not seem to be supported.

**Comment by lfrancois** [comment]
Why did you decide to remove this from the `develop` version of kbox? I guess it would be great to get as much data as possible on the n2k network.

**Comment by sarfata** [comment]
@lfrancois it's back in #49

**Comment by sarfata** [comment]
Actually, it's back in develop. In the new PR, it will also be sent via WiFi TCP (NMEA) and WebSocket (signalk).
