### ISSUE TITLE
As a user, I expect NMEA pitch/roll sentence to work with OpenCPN

### ISSUE THREAD

**Issue by sarfata** [sarfata/kbox-firmware#63]
See Ron's work here:
https://github.com/sarfata/kbox-firmware/pull/61/files#diff-e1a852b1882fac49cb1e32e9192d85e1R70

And @ronzeiller work here:
https://github.com/ronzeiller/kbox-firmware-teensy36/blob/master/src/common/signalk/SKNMEAVisitor.cpp#L60

Official doc on what OpenCPN supports: https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:advanced_features:nmea_sentences

**Comment by ronzeiller** [comment]
Sent PR for sentence for openCPN and Expedition, both tested.
May be  settings for NMEA0183 should be possible to make (configurator) as there are some deprecated NMEA0183 sentences but some programs still wants them....
May be your PITCH/ROLL sentence with the 12 fields is still necessary for some old programs or displays.
