### ISSUE TITLE
As a user, I expect Pressure in NMEA sentence to be compatible with OpenCPN

### ISSUE THREAD

**Issue by sarfata** [sarfata/kbox-firmware#69]
[OpenCPN doc says](https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:advanced_features:nmea_sentences):

Measured Value | Transducer Type | Measured Data   | Unit of measure | Transducer Name
-----------------|------------------|-----------------|-----------------|----------------------------
barometric     | "P" pressure    | 0.8..1.1 or 800..1100           | "B" bar         | "Barometer"

We should be publishing in Bars, which should work but Ron had to make a change to get this to work:
https://github.com/sarfata/kbox-firmware/pull/61/files#diff-e1a852b1882fac49cb1e32e9192d85e1R57

**Comment by ronzeiller** [comment]
I think Ron is right.
In KBox the sensor gives Pascal and also Signal K is Pascal which is ok.
The  NMEA0183 building gets Pascal too, but here it should be bar
So 1/100000 should be right

May be also a new define in SKUnits.h?
#define SKPascalToBar(x)   x / 1000000
