### ISSUE TITLE
Supported PGNs

### ISSUE THREAD

**Issue by usauerbrey** [sarfata/kbox-firmware#7]
Just to add to the wiki:
you wrote:  "Barometric pressure, temperature and humidity all ok on Raymarine i70 display. The display does not support "inside temperature" 
This is true, but also i70 does not support "inside humidity". Is is the same as with temperature, only "outside humidity" is supported.

**Comment by sarfata** [comment]
Thanks! Updated the wiki! Sorry it took so long - I missed the notification here!
