### ISSUE TITLE
Voltage Readings

### ISSUE THREAD

**Issue by ronzeiller** [sarfata/kbox-firmware#87]
Thomas,
I was trying now for hours to find out why the voltage reading in "my T36" KBox is not working, but without result.

The strange thing is, I do not see any difference between master-branch and develop-branch.
In master-branch it is working and in develop I get 0.0V

**Comment by ronzeiller** [comment]
Sorry, it was a stupid mistake!!!
In my Box I have CAN Standby on the same pin as Supply battery, so the pulldown made 0V
(today I changed pins to become compatible with original KBox again and I forgot the CAN.... :shit:)

**Comment by ronzeiller** [comment]
Just found out, that it is not possible to change the pin, because on the T3.6 Pin A14 = pin 33

Would you mind if we put into the `board.c `something like:
```
/* CAN Transceiver */
#if defined (__MK66FX1M0__)
  static const pin_t can_standby = 32;
#else
  static const pin_t can_standby = 33;
#endif
```
Just for the next 100s of PRs? :-)
Thank You!

**Comment by sarfata** [comment]
No problem. I think the best way is to use a `#ifdef BOARD_RONZEILLER` (or something like this) and to add a `-DBOARD_RONZEILLER` in the build flags of your environment (in platformio.ini).

Two reasons:
 - There is already some `#ifdef BOARD_v1_revA` (for the first prototypes of KBox)
 - If I make a version with the teensy 3.6 later, the test on CPU would not be enough to differentiate your board from mine.

**Comment by ronzeiller** [comment]
No problem, I think I can wait until you will do a teensy 3.6 version :-)
(Otherwise I would have to change the platformio.ini every time....)
